# Generated by Django 2.2.1 on 2019-10-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
